---
- hosts: webservers
  remote_user: root
  gather_facts: False
  tasks:
    - name: Edit /etc/hostname
      hostname: name={{ inventory_hostname }}
    - name: Edit /etc/hosts 
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1       {{ inventory_hostname }}'
        owner: root
        group: root
        mode: 0644
    - name: Configure interface
      net_interface:
        name: eth0
        mtu: 1440
        enabled: True
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
    - name: Install Latest nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Start nginx
      service:
        name: nginx
        state: started
    # - name: copy the nginx config file and restart nginx
    #   copy:
    #     src: /home/mininet/static_site.cfg
    #     dest: /etc/nginx/sites-available/static_site.cfg
    # - name: create symlink
    #   file:
    #     src: /etc/nginx/sites-available/static_site.cfg
    #     dest: /etc/nginx/sites-enabled/default
    #     state: link
    # - name: copy the content of the web site
    #   copy:
    #     src: /home/mininet/static-site-src/
    #     dest: /home/mininet/static-site
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
