---
- hosts: webservers
  remote_user: root
  gather_facts: False
  tasks:
    - name: Edit /etc/hostname
      hostname: name={{ inventory_hostname }}
    - name: Edit /etc/hosts 
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1       {{ inventory_hostname }}'
        owner: root
        group: root
        mode: 0644
    - name: Configure interface
      command: /sbin/ifconfig eth0 mtu 1440 up
    - name: Update
      command: /usr/bin/apt-get update --force-yes
    # - name: Upgrade all packages to the latest version
    #   apt:
    #     name: "*"
    #     force: yes
    #     state: latest
    - name: Install Latest nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Start nginx
      service:
        name: nginx
        state: started
    # - name: copy the nginx config file and restart nginx
    #   copy:
    #     src: /home/mininet/static_site.cfg
    #     dest: /etc/nginx/sites-available/static_site.cfg
    # - name: create symlink
    #   file:
    #     src: /etc/nginx/sites-available/static_site.cfg
    #     dest: /etc/nginx/sites-enabled/default
    #     state: link
    # - name: copy the content of the web site
    #   copy:
    #     src: /home/mininet/static-site-src/
    #     dest: /home/mininet/static-site
    - name: Remove IPv6
      lineinfile:
        path: /etc/nginx/sites-enabled/default
        regexp: '^ipv6only'
        line: '# listen [::]:80 default_server ipv6only=on;'
    - name: Set Nginx user
      lineinfile: 
        dest: /etc/nginx/nginx.conf
        regexp: "^user"
        line: "user {{ inventory_hostname }};"
        state: present
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
